In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
# Load Data
url = "https://raw.githubusercontent.com/martj42/international_results/master/results.csv"

df = pd.read_csv(url)

df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [3]:
# Basic Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49329 entries, 0 to 49328
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49329 non-null  object
 1   home_team   49329 non-null  object
 2   away_team   49329 non-null  object
 3   home_score  49257 non-null  float64
 4   away_score  49257 non-null  float64
 5   tournament  49329 non-null  object
 6   city        49329 non-null  object
 7   country     49329 non-null  object
 8   neutral     49329 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

In [4]:
# Basic Dataset Numerical Stats
df.describe()

        home_score    away_score
count  49257.00000  49257.000000
mean       1.75705      1.182735
std        1.77490      1.403175
min        0.00000      0.000000
25%        1.00000      0.000000
50%        1.00000      1.000000
75%        2.00000      2.000000
max       31.00000     21.000000

In [5]:
df.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')

### Basic Data Cleaning

In [6]:
# ------ DATA CLEANING ------
# Rename Columns appropriately
df = df.rename(columns={
    "home_score": "home_goals", 
    "away_score": "away_goals", 
})

# Convert date column to datetime data type
df["date"] = pd.to_datetime(df["date"])
df = df.sort_values("date")

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49329 entries, 0 to 49328
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49329 non-null  datetime64[ns]
 1   home_team   49329 non-null  object
 2   away_team   49329 non-null  object
 3   home_goals  49257 non-null  float64
 4   away_goals  49257 non-null  float64
 5   tournament  49329 non-null  object
 6   city        49329 non-null  object
 7   country     49329 non-null  object
 8   neutral     49329 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(5)
memory usage: 3.4+ MB

##### Handle Missing Values

In [8]:
# Missing Values Check
df.isna().sum()

date           0
home_team      0
away_team      0
home_goals    72
away_goals    72
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [9]:
# Drop missing values from goals columns (home_goals & away_goals)
df = df.dropna(subset=['home_goals', 'away_goals'])

##### Convert Goals(Home/Away) to integer data type

In [10]:
# Convert home_goals & away_goals variables int not float
df['home_goals'] = df['home_goals'].astype(int)
df['away_goals'] = df['away_goals'].astype(int)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49257 entries, 0 to 49223
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49257 non-null  datetime64[ns]
 1   home_team   49257 non-null  object
 2   away_team   49257 non-null  object
 3   home_goals  49257 non-null  int64
 4   away_goals  49257 non-null  int64
 5   tournament  49257 non-null  object
 6   city        49257 non-null  object
 7   country     49257 non-null  object
 8   neutral     49257 non-null  bool
dtypes: bool(1), datetime64[ns](1), int64(2), object(5)
memory usage: 3.4+ MB

In [13]:
df = df.reset_index(drop=True)

##### Save Clean Data

In [14]:
output_path = "../data/processed/matches_clean.csv"
df.to_csv(output_path, index=False)

print(f"Cleaned Matches Data Saved to location: {output_path}")

Cleaned Matches Data Saved to location: ../data/processed/matches_clean.csv